fn main() {
    relm4_icons_build::bundle_icons(
        "icon_names.rs",
        Some("com.github.nocrex.tf2demoplayer"),
        None::<&str>,
        Some("icons"),
        [
            "play-large",
            "pin-location",
            "stop-large",
            "skip-backwards-30",
            "skip-forward-30",
            "share",
            "list-compact",
            "cross-small-circle-outline",
            "arrow-pointing-at-line-down",
            "plus",
            "minus",
            "edit",
            "settings",
            "folder-open",
            "menu",
            "user-trash",
            "arrow-circular-top-right",
            "search-folder",
        ],
    );
}
