icons = [
    "skip-backwards-30",
    "skip-forward-30",
    "video-clip",
    "cross-small-circle-outline",
    "search-folder",
    "list-compact",
    "people",
    "chat-bubbles-text",
    "symbolic-link",
    "copy",
    "info-outline",
    "list-large",
    "violence3",
    "network-server",
    "flag-filled",
    "check-round-outline",
    "horizontal-arrows",
    "discover",
]